### ISSUE TITLE
Bug in JSD?

### ISSUE THREAD

**Issue by richelbilderbeek** [thijsjanzen/nodeSub#8]
Hi @thijsjanzen,

AFAICS, the JSD in RPANDA does not always work, see [my bug report here](https://github.com/hmorlon/PANDA/issues/23).

Just that you know you may find some `NaN`s in your results :+1:

**Comment by thijsjanzen** [comment]
Thanks for the heads-up!

It seems this is caused by the spectral density, that is, the density approximation of the distribution of 'tree eigen values', spanning towards negative values.
Then, the JSD is calculated using a square root function, which fails on negative values.

I'm not sure what causes this in the trees themselves though... e.g. what property of the tree triggers negative eigenvalues. 

Also, I noticed that JSD doesn't work well when comparing trees that are extremely different (e.g. have an order of magnitude difference in branching times)

**Comment by richelbilderbeek** [comment]
> Also, I noticed that JSD doesn't work well when comparing trees that are extremely different (e.g. have an order of magnitude difference in branching times)

I think the RPANDA people would appreciation another reprex there :+1:

**Comment by thijsjanzen** [comment]
> > Also, I noticed that JSD doesn't work well when comparing trees that are extremely different (e.g. have an order of magnitude difference in branching times)
> 
> I think the RPANDA people would appreciation another reprex there 👍

I understand, but I think this error was mainly driven by a failure from my side to specify the clock rate in inferring trees, not necessarily a RPANDA issue.
